In [22]:
import numpy as np

def array_factory(mode, shape, value=None):
    """Generate array by mode: zeros, ones, full, or identity."""
    if mode == "zeros":
        return np.zeros(shape)
    elif mode == "ones":
        return np.ones(shape)
    elif mode == "full":
        if value is None:
            raise ValueError("Parameter 'value' is required for mode 'full'")
        return np.full(shape, value)
    elif mode == "identity":
        size = shape[0] if isinstance(shape, (tuple, list)) else shape
        return np.identity(size)
    else:
        raise ValueError(f"Unknown mode: {mode}")

print("Zeros Matrix (2x3):\n", array_factory("zeros", (2, 3)))
print("\nOnes Matrix (2x2):\n", array_factory("ones", (2, 2)))
print("\nFull Matrix (2x3 with 7):\n", array_factory("full", (2, 3), value=7))
print("\nIdentity Matrix (3x3):\n", array_factory("identity", 3))

Zeros Matrix (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix (2x2):
 [[1. 1.]
 [1. 1.]]

Full Matrix (2x3 with 7):
 [[7 7 7]
 [7 7 7]]

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
def secure_reshape_and_stack(data1, data2, new_shape):
    """Reshape data1 and vertically stack with data2."""
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        
        reshaped_arr1 = arr1.reshape(new_shape)
        combined_dataset = np.vstack((reshaped_arr1, arr2))
        
        return combined_dataset
    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

branch_a = [1, 2, 3, 4, 5, 6]
branch_b = [[7, 8, 9], [10, 11, 12]]

final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print("Stacked Dataset (4x3):\n", final_report)

Stacked Dataset (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
def apply_threshold(arr, threshold, replacement_value=-1):
    """Replace values >= threshold with replacement_value."""
    arr = np.array(arr)
    condition = arr >= threshold
    return np.where(condition, replacement_value, arr)

# --- Test Part 3 ---
v = np.array([1, 2, 3])
print("Threshold Test 1:", apply_threshold(v, 2, -20))

readings = [25, 30, 85, 22, 90]
print("Threshold Test 2:", apply_threshold(readings, threshold=80, replacement_value=-1))

Threshold Test 1: [  1 -20 -20]
Threshold Test 2: [25 30 -1 22 -1]
